version: '3.8'

services:
  fushion-fe:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BASE_URL=${VITE_BASE_URL}
networks:
  default:
    name: frontend
    external: true